---
- name: Copy across GPG secret key.
  copy: content={{ mysql_restore_gpg_secret_key }} dest={{ mysql_restore_gpg_secret_dest }}

- name: Import GPG secret key into keyring.
  command: gpg --allow-secret-key-import --import {{ mysql_restore_gpg_secret_dest }}
  register: gpg_result
  failed_when: '"Invalid keyring" in gpg_result.stderr'
  changed_when: '"secret keys imported" in gpg_result.stderr'
