---
- set_fact: mysql_restore_dir_realpath={{ mysql_restore_dir.rstrip('/') | realpath }}

- name: Create folder to store backups.
  file: path={{ mysql_restore_dir_realpath }} state=directory

- name: Determine all imported databases
  shell: find {{ mysql_restore_dir_realpath }} -name "*.imported" -exec basename {} \; | cut -d "." -f 1
  register: mysql_restore_imported_result
  changed_when: False

- set_fact: mysql_restore_imported={{ mysql_restore_imported_result.stdout_lines | default([]) }}
